# Generated by Django 5.1 on 2024-08-19 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binge', '0002_platform_alter_movie_director_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='site',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform', to='binge.movie'),
        ),
    ]
