# Generated by Django 5.1 on 2024-08-19 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binge', '0003_platform_site_alter_platform_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='platform',
        ),
        migrations.AddField(
            model_name='movie',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='binge.platform'),
            preserve_default=False,
        ),
    ]
